# Generated by Django 5.1.6 on 2025-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updateed',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
